services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    volumes:
      - map-of-music_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  crawler:
    build: ./Crawler
    profiles: ["tools"]  # <--- This hides it
    env_file: .env
    depends_on:
      db: { condition: service_healthy }

  similaritymap:
    build: ./SimilarityMap
    profiles: ["tools"]  # <--- This hides it
    env_file: .env
    depends_on:
      db: { condition: service_healthy }
    command: ["--method", "networkx", "--iterations", "500"]
  
  api:
    build: ./Api
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build: ./Frontend # See Dockerfile below
    restart: always
  
  gateway:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - api
      - frontend

volumes:
  map-of-music_pgdata:
    external: true
  caddy_data: